cage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:scp_id>/", views.detail, name="detail"),
    path("locations/", views.place, name="locations"),
    # path("locations/sightings/", views.sightings, name="sightings"),
    path("locations/sightings/<int:location_id>/", views.sightings, name="sightings"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('subjects/', include('cage.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), #for the login page :)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#added these lines to redirect for images
#from django.conf import settings
#from django.conf.urls.static import static
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cage/models.py
from django.db import models

safety_level = (
    ('SAFE', 'Safe'),
    ('EUCLID', 'Euclid'),
    ('KETER', 'Keter'),
)

class Monster(models.Model):
    monster_name = models.CharField(max_length=50)
    behaviour_type = models.CharField(choices=safety_level, max_length=6)
    # image = models.ImageField(upload_to ='', default='/default0.png')
    image = models.URLField(default='https://agile-shore-66300.herokuapp.com/static/cage/img/monsters/default0.png')
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.monster_name

class Location(models.Model):
    name = models.CharField(max_length=50)
    monsters = models.ManyToManyField(Monster)

    def __str__(self):
        return self.name

cage/views.py
from django.shortcuts import render, redirect
from .models import Monster
from .models import Location
from django.http import HttpResponse

def index(request):
    context = {"monsters": Monster.objects.all()}
    return render (request, "cage/index.html", context)

def detail(request, scp_id):
    context = {"monster": Monster.objects.get(pk=scp_id)}
    return render (request, "cage/profile.html", context)

def place(request):
    context = {"locations": Location.objects.all()}
    return render (request, "cage/locations.html", context)

def sightings(request, location_id):
    l = Location.objects.get(pk=location_id)
    monsters = Monster.objects.filter(location=l)
    context = {"monsters": monsters}
    return render (request, "cage/sightings.html", context)
    # print(context)

# return HttpResponse(m.monster_name)

cage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'main.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Baumans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="header">
            <img id="logo" src="{% static 'cage/img/scplogo01.png' %}">
            <h1>SCP Foundation</h1>™
            <ul>
                <li><a href="/subjects/">Subjects</a></li>
                <li><a href="/subjects/locations/">Locations</a></li>
                <li><a href="/accounts/login/">Login</a><li>
            </ul>
        </div>
        {% block content %}{% endblock %}
    </body>
</html>

cage/templates/cage/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} SCP {% endblock %}
{% block content %}
<div id="allMonsters">
    {% for Monster in monsters %}
    <div class="polaroid">
        <a href="{% url 'detail' Monster.id %}">
            <img src="{{ Monster.image }}"></a><br>
        <div id="note"> {{Monster.monster_name}}</div>
    </div>
    {% empty %}
    No Monster
    {% endfor %}

    {% endblock %}
</div>

cage/templates/cage/locations.html
{% extends "base.html" %}
{% load static %}
{% block title %} NOT NCP {% endblock %}
{% block content %}
<br><br>
<div id="locationPage">
    <div id="knownLocations">
        <br>
        KNOWN LOCATIONS:
        {% for location in locations %}
        <a href="{% url 'sightings' location.id %}">
            <div class="hw">{{ location.name }}</div>
        </a>
        {% empty %}
        No Locations
        {% endfor %}
    </div>
    <div id="mapDiv">
        <img id="map" src="/static/cage/img/map0.jpg">
    </div>
</div>

<body onload="document.body.className += ' loaded';" class="fadein"></body>
{% endblock %}

cage/templates/cage/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %} Subject: {{monster.monster_name}}{% endblock %}
{% block content %}
<br><br>
<div id="profilePage">
    <div class="vl"></div>
    <div class="v2"></div>
    <div id="profileTitle">
        <h1>SCP</h1>
        <h2>Secure. Contain. Protect</h2>
    </div>
    <br>
    <img id="profileClip" src="{% static 'cage/img/clip.png' %}">
    <img id="profilePic" src="{{ monster.image }}">
    <div id="profileInfo">
        <div id=profileName>NAME:
            <div class="hw">{{monster.monster_name}}</div>
            <br><br>
            TYPE:
            <div class="hw">{{monster.behaviour_type}}</div>
            <br><br>
            DISCOVERED:
            <div class="hw">{{monster.date}}</div>
            <br><br>
            DESCRIPTION:
            <div class="hw">{{monster.description}}</div>
            <br><br>
            KNOWN LOCATIONS:
            {% for location in monster.location_set.all %}
            <br><br>
            <a href="{% url 'detail' location.id %}">
                <div class="hw">{{location.name}}</div>
            </a>
            {% empty %}
            No Locations
            {% endfor %}
        </div>
    </div>
</div>

<body onload="document.body.className += ' loaded';" class="fadein"></body>
{% endblock %}

cage/templates/cage/sightings.html
{% extends "base.html" %}
{% load static %}
{% block title %} Subject: {{monster.monster_name}}{% endblock %}
{% block content %}

SIGHTINGS HERE:
        {% for monster in monsters.all %}
        <div class="hw">{{monster}}</div>
        {% empty %}
        LOCATIONS COMING SOON!
        {% endfor %}

{% endblock %}